"""Three projections of one spec: YAML, R, Python.

Gretl's command log is one of its best ideas, and we keep the spirit -- but the
spec is the source of truth and the scripts are generated from it. A hand-edited
script forks into a "custom" analysis that must still return the canonical
result schema.
"""

from __future__ import annotations

import json
from pprint import pformat
from typing import Any

import yaml

HEADER = """# Generated by Causal Capybara {version}.
# This script is a projection of the study spec, not the other way round.
# Editing it forks the analysis: a custom script must still return a
# capy.result.v1 record before it can enter a comparison.
"""


def spec_yaml(spec: dict[str, Any]) -> str:
    return yaml.safe_dump(_clean(spec), sort_keys=False, allow_unicode=True)


def _clean(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {k: _clean(v) for k, v in obj.items() if v not in (None, [], {}) or k in ("cutoff",)}
    if isinstance(obj, list):
        return [_clean(v) for v in obj]
    return obj


def _r_str(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, (list, tuple)):
        return "c(" + ", ".join(_r_str(v) for v in value) + ")"
    return json.dumps(str(value))


def _r_formula(outcome: str, terms: list[str]) -> str:
    rhs = " + ".join(terms) if terms else "1"
    return f"{outcome} ~ {rhs}"


# ---------------------------------------------------------------------------
# Python projection -- runs through the same adapters the GUI runs
# ---------------------------------------------------------------------------


def python_script(spec: dict[str, Any], *, method_id: str | None = None, version: str = "0.1.0",
                  data_path: str | None = None) -> str:
    methods = _methods_of(spec, method_id)
    body = [
        HEADER.format(version=version),
        "import json",
        "import pandas as pd",
        "from capy_py.contracts import run_method",
        "",
        f"DATA = {json.dumps(data_path or 'data/analysis.parquet')}",
        f"SEED = {int(spec['seed'] if spec.get('seed') is not None else 20260830)}",
        "",
        "SPEC = " + _py_literal(_clean(spec)),
        "",
        "df = pd.read_parquet(DATA)",
        "",
        "for method_id, options in [",
    ]
    for m in methods:
        body.append(f"    ({json.dumps(m['method_id'])}, {_py_literal(m.get('options') or {})}),")
    body += [
        "]:",
        "    result = run_method(method_id, SPEC, df, seed=SEED, options=options)",
        "    print(result['method_label'], result['estimate'], result['ci_low'], result['ci_high'])",
        "    with open(f\"{result['run_id']}.json\", 'w', encoding='utf-8') as fh:",
        "        json.dump(result, fh, indent=2)",
        "",
    ]
    return "\n".join(body)


def _py_literal(obj: Any, indent: int = 0) -> str:
    # Python syntax must be produced structurally: replacing JSON tokens in
    # strings can change variable names and leaves nested boolean lists invalid.
    text = pformat(obj, width=88, sort_dicts=False)
    if indent:
        pad = " " * indent
        text = "\n".join(pad + line if i else line for i, line in enumerate(text.splitlines()))
    return text


# ---------------------------------------------------------------------------
# R projection -- the packages a researcher would otherwise reach for
# ---------------------------------------------------------------------------


def r_script(spec: dict[str, Any], *, method_id: str | None = None, version: str = "0.1.0",
             data_path: str | None = None) -> str:
    roles = spec.get("roles") or {}
    methods = _methods_of(spec, method_id)
    lines = [
        HEADER.format(version=version).replace("#", "#", 1),
        'library(arrow)',
        "",
        f'data_path <- {json.dumps(data_path or "data/analysis.parquet")}',
        f"set.seed({int(spec['seed'] if spec.get('seed') is not None else 20260830)})",
        "d <- as.data.frame(arrow::read_parquet(data_path))",
        "",
    ]
    subset = ((spec.get("sample") or {}).get("subset_expr"))
    if subset:
        lines.append(f"# population filter, exactly as recorded in the spec")
        lines.append(f"d <- subset(d, {subset})")
        lines.append("")
    for m in methods:
        snippet = _R_SNIPPETS.get(m["method_id"])
        lines.append(f"## {m['method_id']}")
        if snippet is None:
            lines.append(
                f"# No R projection for {m['method_id']} yet. The Python engine ran this one;\n"
                f"# see the Code tab's Python projection, or fork a custom R script that returns\n"
                f"# a capy.result.v1 record."
            )
        else:
            try:
                lines.append(snippet(roles, m.get("options") or {}, spec))
            except Exception as exc:  # a bad projection must not break the tab
                lines.append(f"# Could not project this method to R: {exc}")
        lines.append("")
    return "\n".join(lines)


def _confounders(roles: dict[str, Any]) -> list[str]:
    forbidden = set(roles.get("forbidden") or [])
    return [c for c in (roles.get("confounders") or []) if c not in forbidden]


def _s_outcome_reg(roles, opts, spec) -> str:
    y, d = roles.get("outcome"), roles.get("treatment")
    x = _confounders(roles)
    return (
        "library(marginaleffects)\n"
        f"fit <- lm({_r_formula(y, [d] + x)}, data = d)\n"
        f"avg_comparisons(fit, variables = {_r_str(d)},\n"
        f"                newdata = {'subset(d, ' + d + ' == 1)' if (spec.get('estimand') == 'ATT') else 'd'})"
    )


def _s_match_nn(roles, opts, spec) -> str:
    y, d = roles.get("outcome"), roles.get("treatment")
    x = _confounders(roles)
    caliper = opts.get("caliper")
    return (
        "library(MatchIt); library(cobalt); library(marginaleffects)\n"
        f"m <- matchit({_r_formula(d, x)}, data = d,\n"
        f"             method = \"nearest\", distance = \"glm\",\n"
        f"             estimand = {_r_str(spec.get('estimand') or 'ATT')},\n"
        f"             ratio = {int(opts.get('ratio', 1))},\n"
        f"             replace = {_r_str(bool(opts.get('replacement', False)))}"
        + (f",\n             caliper = {float(caliper)}" if caliper else "")
        + ")\n"
        "love.plot(m, stats = \"mean.diffs\", abs = TRUE, thresholds = 0.1)\n"
        "md <- match.data(m)\n"
        f"fit <- lm({_r_formula(y, [d] + x)}, data = md, weights = md$weights)\n"
        f"avg_comparisons(fit, variables = {_r_str(d)}, wts = \"weights\",\n"
        f"                vcov = ~subclass)"
    )


def _s_cem(roles, opts, spec) -> str:
    d = roles.get("treatment")
    x = _confounders(roles)
    return (
        "library(MatchIt); library(cobalt)\n"
        f"m <- matchit({_r_formula(d, x)}, data = d, method = \"cem\",\n"
        f"             estimand = {_r_str(spec.get('estimand') or 'ATT')})\n"
        "summary(m); love.plot(m, abs = TRUE)"
    )


def _s_ipw(roles, opts, spec) -> str:
    y, d = roles.get("outcome"), roles.get("treatment")
    x = _confounders(roles)
    est = {"ate": "ATE", "att": "ATT", "atc": "ATC", "ato": "ATO"}.get(
        str(opts.get("weight_type", "att")).lower(), spec.get("estimand") or "ATT")
    return (
        "library(WeightIt); library(cobalt); library(survey)\n"
        f"w <- weightit({_r_formula(d, x)}, data = d, method = \"glm\", estimand = {_r_str(est)})\n"
        "bal.tab(w, un = TRUE); love.plot(w, abs = TRUE, thresholds = 0.1)\n"
        "des <- svydesign(ids = ~1, weights = ~w$weights, data = d)\n"
        f"summary(svyglm({_r_formula(y, [d])}, design = des))"
    )


def _s_entropy(roles, opts, spec) -> str:
    d = roles.get("treatment")
    x = _confounders(roles)
    return (
        "library(WeightIt); library(cobalt)\n"
        f"w <- weightit({_r_formula(d, x)}, data = d, method = \"ebal\",\n"
        f"              estimand = {_r_str(spec.get('estimand') or 'ATT')})\n"
        "bal.tab(w, un = TRUE)"
    )


def _s_aipw(roles, opts, spec) -> str:
    y, d = roles.get("outcome"), roles.get("treatment")
    x = _confounders(roles)
    return (
        "library(PSweight)\n"
        f"ps <- {_r_formula(d, x)}\n"
        f"out <- {_r_formula(y, x)}\n"
        f"fit <- PSweight(ps.formula = ps, yname = {_r_str(y)}, data = d,\n"
        f"                augmentation = TRUE, out.formula = out,\n"
        f"                weight = {_r_str('IPW' if (spec.get('estimand') == 'ATE') else 'treated')})\n"
        "summary(fit)"
    )


def _s_did_2x2(roles, opts, spec) -> str:
    y, d = roles.get("outcome"), roles.get("treatment")
    unit, time = roles.get("unit"), roles.get("time")
    cluster = roles.get("cluster") or unit
    return (
        "library(fixest)\n"
        f"feols({y} ~ {d} | {unit} + {time}, data = d, cluster = ~{cluster})"
    )


def _s_twfe(roles, opts, spec) -> str:
    return (
        _s_did_2x2(roles, opts, spec)
        + "\n# Under staggered adoption with heterogeneous effects this coefficient is a\n"
          "# weighted average of 2x2 comparisons whose weights can be negative\n"
          "# (Goodman-Bacon 2021; de Chaisemartin & D'Haultfoeuille 2020).\n"
          "# Report it beside did.callaway_santanna or did.sun_abraham, not instead of them."
    )


def _s_event_study(roles, opts, spec) -> str:
    y, d = roles.get("outcome"), roles.get("treatment")
    unit, time = roles.get("unit"), roles.get("time")
    cluster = roles.get("cluster") or unit
    return (
        "library(fixest)\n"
        f"# relative time is built from the first period each {unit} turns on\n"
        f"d <- transform(d, .first = ave(ifelse({d} == 1, {time}, NA), {unit},\n"
        f"                               FUN = function(v) suppressWarnings(min(v, na.rm = TRUE))))\n"
        f"d$rel <- d${time} - d$.first\n"
        f"es <- feols({y} ~ i(rel, ref = -1) | {unit} + {time}, data = d, cluster = ~{cluster})\n"
        "iplot(es)"
    )


def _s_cs(roles, opts, spec) -> str:
    y, d = roles.get("outcome"), roles.get("treatment")
    unit, time = roles.get("unit"), roles.get("time")
    x = _confounders(roles)
    xf = (" + ".join(x)) if x else "1"
    return (
        "library(did)\n"
        f"d <- transform(d, .g = ave(ifelse({d} == 1, {time}, NA), {unit},\n"
        f"                           FUN = function(v) suppressWarnings(min(v, na.rm = TRUE))))\n"
        "d$.g[is.na(d$.g)] <- 0\n"
        f"att <- att_gt(yname = {_r_str(y)}, tname = {_r_str(time)}, idname = {_r_str(unit)},\n"
        f"               gname = \".g\", xformla = ~ {xf}, data = d,\n"
        f"               control_group = {_r_str(opts.get('control_group', 'nevertreated'))},\n"
        f"               est_method = {_r_str(opts.get('est_method', 'dr'))})\n"
        "summary(aggte(att, type = \"simple\"))\n"
        "ggdid(aggte(att, type = \"dynamic\"))"
    )


def _s_sunab(roles, opts, spec) -> str:
    y, d = roles.get("outcome"), roles.get("treatment")
    unit, time = roles.get("unit"), roles.get("time")
    cluster = roles.get("cluster") or unit
    return (
        "library(fixest)\n"
        f"d <- transform(d, .g = ave(ifelse({d} == 1, {time}, NA), {unit},\n"
        f"                           FUN = function(v) suppressWarnings(min(v, na.rm = TRUE))))\n"
        "d$.g[is.na(d$.g)] <- 10000\n"
        f"sa <- feols({y} ~ sunab(.g, {time}) | {unit} + {time}, data = d, cluster = ~{cluster})\n"
        "summary(sa, agg = \"att\"); iplot(sa)"
    )


def _s_bacon(roles, opts, spec) -> str:
    y, d = roles.get("outcome"), roles.get("treatment")
    unit, time = roles.get("unit"), roles.get("time")
    return (
        "library(bacondecomp)\n"
        f"bacon({_r_formula(y, [d])}, data = d, id_var = {_r_str(unit)}, time_var = {_r_str(time)})"
    )


def _s_rd(roles, opts, spec) -> str:
    y, x = roles.get("outcome"), roles.get("running")
    c = roles.get("cutoff")
    fuzzy = roles.get("treatment")
    args = f"y = d${y}, x = d${x}, c = {_r_str(c)}"
    if fuzzy:
        args += f", fuzzy = d${fuzzy}"
    if opts.get("bandwidth"):
        args += f", h = {float(opts['bandwidth'])}"
    if opts.get("kernel"):
        args += f", kernel = {_r_str(opts['kernel'])}"
    if opts.get("poly_order"):
        args += f", p = {int(opts['poly_order'])}"
    return (
        "library(rdrobust); library(rddensity)\n"
        f"summary(rdrobust({args}))\n"
        f"rdplot(y = d${y}, x = d${x}, c = {_r_str(c)})\n"
        f"summary(rddensity(X = d${x}, c = {_r_str(c)}))"
    )


def _s_sc(roles, opts, spec) -> str:
    y, unit, time = roles.get("outcome"), roles.get("unit"), roles.get("time")
    treated, event = roles.get("treated_unit"), roles.get("event_time")
    return (
        "library(tidysynth)\n"
        "sc <- d |>\n"
        f"  synthetic_control(outcome = {y}, unit = {unit}, time = {time},\n"
        f"                    i_unit = {_r_str(treated)}, i_time = {_r_str(event)},\n"
        "                    generate_placebos = TRUE) |>\n"
        f"  generate_predictor(time_window = min(d${time}):{_r_str(event)}) |>\n"
        "  generate_weights() |>\n"
        "  generate_control()\n"
        "sc |> plot_trends(); sc |> plot_placebos(); sc |> grab_signficance()"
    )


def _s_iv(roles, opts, spec) -> str:
    y, d_ = roles.get("outcome"), roles.get("treatment")
    z = roles.get("instruments") or []
    x = _confounders(roles)
    rhs = " + ".join(x + [d_]) if x else d_
    inst = " + ".join(x + list(z)) if x else " + ".join(z)
    return (
        "library(ivreg)\n"
        f"fit <- ivreg({y} ~ {rhs} | {inst}, data = d)\n"
        "summary(fit, diagnostics = TRUE)   # weak instruments, Wu-Hausman, Sargan"
    )


def _s_its(roles, opts, spec) -> str:
    y, t = roles.get("outcome"), roles.get("time")
    event = roles.get("event_time")
    return (
        "library(nlme); library(sandwich); library(lmtest)\n"
        f"d$post <- as.numeric(d${t} >= {_r_str(event)})\n"
        f"d$since <- pmax(0, d${t} - {_r_str(event)})\n"
        f"fit <- lm({y} ~ {t} + post + since, data = d)\n"
        "coeftest(fit, vcov = NeweyWest(fit))"
    )


def _s_grf(roles, opts, spec) -> str:
    y, d_ = roles.get("outcome"), roles.get("treatment")
    x = _confounders(roles) + list(roles.get("effect_modifiers") or [])
    return (
        "library(grf)\n"
        f"X <- as.matrix(d[, {_r_str(x)}])\n"
        f"cf <- causal_forest(X, d${y}, d${d_})\n"
        "average_treatment_effect(cf, target.sample = \"treated\")\n"
        "test_calibration(cf); rank_average_treatment_effect(cf, predict(cf)$predictions)"
    )


def _s_dml(roles, opts, spec) -> str:
    y, d_ = roles.get("outcome"), roles.get("treatment")
    x = _confounders(roles)
    return (
        "library(DoubleML); library(mlr3); library(mlr3learners)\n"
        f"dat <- DoubleMLData$new(d, y_col = {_r_str(y)}, d_cols = {_r_str(d_)}, x_cols = {_r_str(x)})\n"
        "lrn_g <- lrn(\"regr.ranger\"); lrn_m <- lrn(\"classif.ranger\", predict_type = \"prob\")\n"
        "dml <- DoubleMLIRM$new(dat, ml_g = lrn_g, ml_m = lrn_m, n_folds = 5)\n"
        "dml$fit(); dml$summary()"
    )


def _s_tmle(roles, opts, spec) -> str:
    y, d_ = roles.get("outcome"), roles.get("treatment")
    x = _confounders(roles)
    return (
        "library(tmle)\n"
        f"fit <- tmle(Y = d${y}, A = d${d_}, W = d[, {_r_str(x)}])\n"
        "summary(fit)"
    )


def _s_msm(roles, opts, spec) -> str:
    y, d_ = roles.get("outcome"), roles.get("treatment")
    unit, time = roles.get("unit"), roles.get("time")
    x = _confounders(roles)
    return (
        "library(ipw); library(survey)\n"
        f"w <- ipwtm(exposure = {d_}, family = \"binomial\", link = \"logit\",\n"
        f"           numerator = ~ 1, denominator = ~ {' + '.join(x) if x else '1'},\n"
        f"           id = {unit}, tstart = tstart, timevar = {time}, type = \"all\", data = d)\n"
        "d$sw <- w$ipw.weights\n"
        f"des <- svydesign(ids = ~{unit}, weights = ~sw, data = d)\n"
        f"summary(svyglm({_r_formula(y, [d_])}, design = des))"
    )


def _s_mediation(roles, opts, spec) -> str:
    y, d_ = roles.get("outcome"), roles.get("treatment")
    m = (roles.get("mediator") or [None])[0]
    x = _confounders(roles)
    return (
        "library(CMAverse)\n"
        f"cmest(data = d, model = \"gformula\", outcome = {_r_str(y)}, exposure = {_r_str(d_)},\n"
        f"      mediator = {_r_str([m])}, basec = {_r_str(x)},\n"
        "      EMint = TRUE, estimation = \"imputation\", inference = \"bootstrap\", nboot = 200)"
    )


def _s_rct(roles, opts, spec) -> str:
    y, d_ = roles.get("outcome"), roles.get("treatment")
    x = _confounders(roles)
    cluster = roles.get("cluster")
    blocks = (roles.get("strata") or [None])[0]
    args = f"{_r_formula(y, [d_])}, data = d"
    if x:
        args = f"{y} ~ {d_}, covariates = ~ {' + '.join(x)}, data = d"
    if blocks:
        args += f", blocks = {blocks}"
    if cluster:
        args += f", clusters = {cluster}"
    return "library(estimatr)\n" + (
        f"summary(lm_lin({args}))" if x else f"summary(lm_robust({args}))"
    )


def _s_cace(roles, opts, spec) -> str:
    y, d_ = roles.get("outcome"), roles.get("treatment")
    z = (roles.get("instruments") or [None])[0]
    return (
        "library(estimatr)\n"
        f"summary(lm_robust({_r_formula(y, [z])}, data = d))          # ITT\n"
        f"summary(iv_robust({y} ~ {d_} | {z}, data = d))               # CACE"
    )


_R_SNIPPETS = {
    "obs.outcome_regression": _s_outcome_reg,
    "obs.matching.nn": _s_match_nn,
    "obs.matching.cem": _s_cem,
    "obs.weighting.ipw": _s_ipw,
    "obs.weighting.entropy": _s_entropy,
    "obs.aipw": _s_aipw,
    "obs.tmle": _s_tmle,
    "rct.diff_means": _s_rct,
    "rct.stratified": _s_rct,
    "rct.cluster": _s_rct,
    "rct.cace": _s_cace,
    "did.twoway_2x2": _s_did_2x2,
    "did.twfe": _s_twfe,
    "did.event_study": _s_event_study,
    "did.callaway_santanna": _s_cs,
    "did.sun_abraham": _s_sunab,
    "did.goodman_bacon": _s_bacon,
    "rd.local_linear": _s_rd,
    "rd.fuzzy": _s_rd,
    "rd.density_test": _s_rd,
    "sc.abadie": _s_sc,
    "sc.augmented": _s_sc,
    "iv.2sls": _s_iv,
    "iv.liml": _s_iv,
    "iv.weak_robust": _s_iv,
    "its.segmented": _s_its,
    "its.controlled": _s_its,
    "ml.causal_forest": _s_grf,
    "ml.dml_plr": _s_dml,
    "ml.dml_irm": _s_dml,
    "long.msm_iptw": _s_msm,
    "med.natural_effects": _s_mediation,
    "med.interventional": _s_mediation,
}


def _methods_of(spec: dict[str, Any], method_id: str | None) -> list[dict[str, Any]]:
    if method_id:
        for m in spec.get("methods") or []:
            if m.get("method_id") == method_id:
                return [m]
        return [{"method_id": method_id, "options": {}}]
    chosen = [m for m in (spec.get("methods") or []) if m.get("included", True)]
    return chosen or [{"method_id": "obs.outcome_regression", "options": {}}]


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def project_spec(spec: dict[str, Any], *, project: Any = None, method_id: str | None = None) -> dict[str, Any]:
    from . import __version__

    data_path = None
    if project is not None:
        try:
            data_path = str(project.parquet_path)
        except Exception:
            data_path = None
    notes: list[str] = []
    missing_r = [
        m["method_id"] for m in _methods_of(spec, method_id) if m["method_id"] not in _R_SNIPPETS
    ]
    if missing_r:
        notes.append(
            "No R projection yet for: " + ", ".join(sorted(set(missing_r)))
            + ". The Python projection reproduces the run exactly."
        )
    return {
        "yaml": spec_yaml(spec),
        "python": python_script(spec, method_id=method_id, version=__version__, data_path=data_path),
        "r": r_script(spec, method_id=method_id, version=__version__, data_path=data_path),
        "notes": notes,
        "data_path": data_path,
    }
